name: Movies
options: 
  deploymentTarget: 
    iOS: 15.0
  generateEmptyDirectories: true

packages: 
  SnapshotTesting:        
    url: https://github.com/pointfreeco/swift-snapshot-testing.git
    from: 1.9.0

targets: 
  Movies:
    type: application
    platform: iOS
    deploymentTarget: 
      iOS: 15.0
    sources: Movies
    settings:
      base:
        MARKETING_VERSION: "1.0.0"
        SWIFT_VERSION: 5.0
        PRODUCT_BUNDLE_IDENTIFIER: allana.castenharo.Movies
    preBuildScripts:
      - path: swiftgen.sh
        name: SwiftGen
  MoviesTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: 
      iOS: 15.0
    sources: 
      - path: MoviesTests
        excludes: 
          - "**/*.png"
          - "**/__Snapshots__"
    dependencies: 
      - target: Movies
      - package: SnapshotTesting

schemes:
  Movies:
    build: 
      targets:
        Movies: [run, test]
      parallelizeBuild: true
      buildImplicitDependencies: true
    test: 
      gatherCoverageData: true
      coverageTargets: 
        - Movies
      targets: 
        - MoviesTests
